/* sd_character_ids.h -- GENERATED by tools/derive_character_ids.py; do not edit.
 *
 * Every playable character, from the game's own CharacterIDs class, in the
 * order they joined the game: the exact names the save stores after "CharID_".
 * Left out -- an ID with no character content in this build, so not playable:
 *   Android
 */
#ifndef SD_CHARACTER_IDS_H
#define SD_CHARACTER_IDS_H

#define SD_CHARACTER_COUNT 142

static const char *const SD_CHARACTER_IDS[SD_CHARACTER_COUNT] = {
  "Sonic", "Tails", "Knuckles", "Amy", "Silver", "Rouge", "Cream", "Espio", "Big",
  "Vector", "Charmy", "Whisper", "Tangle", "Omega", "Surge", "Jet", "Marine", "Blaze",
  "ClassicSonic", "MetalSonic", "Wave", "Storm", "PhantomRider", "Sinbad", "SirGawain",
  "SirPercival", "KnucklesTheDread", "RustyRose", "ThornRose", "PopstarAmy",
  "SheriffSonic", "TreasureHunterKnuckles", "EliteAgentRouge", "PirateSonic",
  "LunarBlaze", "AllStarAmy", "SluggerSonic", "LinebackerOmega", "WitchRouge",
  "SantaBig", "ElfClassicSonic", "JingleBelleAmy", "Andronic", "Shadow", "Infinite",
  "Darkspine", "SirGalahad", "SirLancelot", "SirLamorak", "PaladinAmy", "KnightTails",
  "PyromancerBlaze", "ChronoSilver", "SonicBoscageMaze", "GrimSonic", "RockstarRouge",
  "BassistBlaze", "DrummerCream", "CaptainShadow", "OutlawShadow", "DetectiveVector",
  "NinjaEspio", "KunoichiRouge", "GladiatorKnuckles", "DulceAmy", "PandaAmy",
  "UnicornCream", "IceCream", "BlossomAmy", "LunarTangle", "ValentineRouge",
  "ValentineWhisper", "ExtremeGearSonic", "ExtremeGearShadow", "ExtremeGearRouge",
  "ExtremeGearSurge", "StrikerSonic", "ReaperMetalSonic", "VampireShadow",
  "MummyKnuckles", "NutcrackerSilver", "ReindeerKnuckles", "SuperSonic",
  "ClassicSuperSonic", "SuperShadow", "SuperSilver", "BurningBlaze", "DoomShadow",
  "ExtremeGearSuperSonic", "RidersSuperShadow", "RidersSuperSilver", "RivalSonic",
  "RivalShadow", "RivalAmy", "SonicAndCaliburn", "ExcaliburSonic",
  "DragonHunterLancelot", "DragonHunterSonic", "WarriorShadow", "ValhallaSurge",
  "RagnarokSilver", "UnicornKnightCream", "LunarSonic", "LunarTails", "Werehog",
  "MetalSonicMach3", "NeoMetalSonic", "Mephiles", "OniMephiles", "CursedSamuraiInfinite",
  "DemonHunterShadow", "SnowdriftSonic", "TailsNine", "IdolSonic", "IdolShadow",
  "FortuneTellerAmy", "JesterSonic", "KarateKnuckles", "Red", "Chuck", "Bomb",
  "MyMelody", "BadtzMaru", "HelloKitty", "Chococat", "PacMan", "MsPacMan", "TeenSonic",
  "BabySonic", "Longclaw", "MovieTails", "MovieKnuckles", "MovieSuperSonic",
  "MovieShadow", "MovieSuperShadow", "TvSeriesKnuckles", "LegoSonic", "LegoAmy",
  "LegoTails", "Bongo", "MovieChuck", "MovieRed",
};

#endif /* SD_CHARACTER_IDS_H */
