/* sd_il2cpp_offsets.h -- GENERATED by tools/derive_il2cpp_hooks.py. Do not edit.
 * Source: dump.cs verified against libil2cpp.so (RVA-Offset delta 0x4000
 * matches the il2cpp section). Every RVA is bounds-checked into an executable
 * section and checked for identical-code folding. W0/W1 are the first two
 * instruction words at each target, verified before any hook is written. */
#ifndef SD_IL2CPP_OFFSETS_H
#define SD_IL2CPP_OFFSETS_H

/* void SetInt(string key, int value) */
#define SD_IL2CPP_PP_SetInt_RVA 0x1F48F90u
#define SD_IL2CPP_PP_SetInt_W0  0xa9bf4ffeu
#define SD_IL2CPP_PP_SetInt_W1  0x97fffe7bu

/* int GetInt(string key, int defaultValue) */
#define SD_IL2CPP_PP_GetInt2_RVA 0x1F48FE8u
#define SD_IL2CPP_PP_GetInt2_W0  0xd10143ffu
#define SD_IL2CPP_PP_GetInt2_W1  0xa90357feu

/* PP_GetInt1: NOT IN THIS BUILD -- int GetInt(string key) */
#define SD_IL2CPP_PP_GetInt1_RVA 0u
#define SD_IL2CPP_PP_GetInt1_W0  0u
#define SD_IL2CPP_PP_GetInt1_W1  0u

/* void SetFloat(string key, float value) */
#define SD_IL2CPP_PP_SetFloat_RVA 0x1F491A4u
#define SD_IL2CPP_PP_SetFloat_W0  0xa9bf4ffeu
#define SD_IL2CPP_PP_SetFloat_W1  0x97fffe66u

/* float GetFloat(string key, float defaultValue) */
#define SD_IL2CPP_PP_GetFloat2_RVA 0x1F491FCu
#define SD_IL2CPP_PP_GetFloat2_W0  0xd10143ffu
#define SD_IL2CPP_PP_GetFloat2_W1  0xfd001be8u

/* void SetString(string key, string value) */
#define SD_IL2CPP_PP_SetString_RVA 0x1F493C4u
#define SD_IL2CPP_PP_SetString_W0  0xa9bf4ffeu
#define SD_IL2CPP_PP_SetString_W1  0x97fffe52u

/* string GetString(string key, string defaultValue) */
#define SD_IL2CPP_PP_GetString2_RVA 0x1F4941Cu
#define SD_IL2CPP_PP_GetString2_W0  0xd10343ffu
#define SD_IL2CPP_PP_GetString2_W1  0xa90b57feu

/* string GetString(string key) */
#define SD_IL2CPP_PP_GetString1_RVA 0x1F49720u
#define SD_IL2CPP_PP_GetString1_W0  0xa9be57feu
#define SD_IL2CPP_PP_GetString1_W1  0xa9014ff4u

/* bool HasKey(string key) */
#define SD_IL2CPP_PP_HasKey_RVA 0x1F49768u
#define SD_IL2CPP_PP_HasKey_W0  0xd10143ffu
#define SD_IL2CPP_PP_HasKey_W1  0xf9001bfeu

/* void DeleteKey(string key) */
#define SD_IL2CPP_PP_DeleteKey_RVA 0x1F49918u
#define SD_IL2CPP_PP_DeleteKey_W0  0xd10143ffu
#define SD_IL2CPP_PP_DeleteKey_W1  0xf9001bfeu

/* void Save() */
#define SD_IL2CPP_PP_Save_RVA 0x1F49ABCu
#define SD_IL2CPP_PP_Save_W0  0xa9bf4ffeu
#define SD_IL2CPP_PP_Save_W1  0xb0002593u

/* int get_touchCount() */
#define SD_IL2CPP_IN_get_touchCount_RVA 0x1F932F4u
#define SD_IL2CPP_IN_get_touchCount_W0  0xa9bf4ffeu
#define SD_IL2CPP_IN_get_touchCount_W1  0xb0002353u

/* Vector3 get_mousePosition() */
#define SD_IL2CPP_IN_get_mousePosition_RVA 0x1F92E1Cu
#define SD_IL2CPP_IN_get_mousePosition_W0  0xd10083ffu
#define SD_IL2CPP_IN_get_mousePosition_W1  0xa9014ffeu

/* bool GetMouseButton(int button) */
#define SD_IL2CPP_IN_GetMouseButton_RVA 0x1F92BB0u
#define SD_IL2CPP_IN_GetMouseButton_W0  0xf81e0ffeu
#define SD_IL2CPP_IN_GetMouseButton_W1  0xa9014ff4u

/* bool GetMouseButtonDown(int button) */
#define SD_IL2CPP_IN_GetMouseButtonDown_RVA 0x1F92BECu
#define SD_IL2CPP_IN_GetMouseButtonDown_W0  0xf81e0ffeu
#define SD_IL2CPP_IN_GetMouseButtonDown_W1  0xa9014ff4u

/* bool GetMouseButtonUp(int button) */
#define SD_IL2CPP_IN_GetMouseButtonUp_RVA 0x1F92C28u
#define SD_IL2CPP_IN_GetMouseButtonUp_W0  0xf81e0ffeu
#define SD_IL2CPP_IN_GetMouseButtonUp_W1  0xa9014ff4u

/* Touch GetTouch(int index) */
#define SD_IL2CPP_IN_GetTouch_RVA 0x1F92C8Cu
#define SD_IL2CPP_IN_GetTouch_W0  0xd101c3ffu
#define SD_IL2CPP_IN_GetTouch_W1  0xa90557feu

/* bool get_touchSupported() */
#define SD_IL2CPP_IN_get_touchSupported_RVA 0x1F93288u
#define SD_IL2CPP_IN_get_touchSupported_W0  0xa9bf4ffeu
#define SD_IL2CPP_IN_get_touchSupported_W1  0xb0002353u

/* int get_width() */
#define SD_IL2CPP_SC_get_width_RVA 0x1F044D0u
#define SD_IL2CPP_SC_get_width_W0  0xa9bf4ffeu
#define SD_IL2CPP_SC_get_width_W1  0xb00027b3u

/* private void SetResolutionScale(float scale) */
#define SD_IL2CPP_AF_SetResolutionScale_RVA 0x0F94198u
#define SD_IL2CPP_AF_SetResolutionScale_W0  0x6dbe23e9u
#define SD_IL2CPP_AF_SetResolutionScale_W1  0xa9014ffeu

/* private bool CanAnalyticsEventsBeCollected(IAnalyticsEvent analyticsEvent) */
#define SD_IL2CPP_AN_CanCollect_RVA 0x14D6BD0u
#define SD_IL2CPP_AN_CanCollect_W0  0xf81d0ffeu
#define SD_IL2CPP_AN_CanCollect_W1  0xa90157f6u

/* int get_height() */
#define SD_IL2CPP_SC_get_height_RVA 0x1F044F8u
#define SD_IL2CPP_SC_get_height_W0  0xa9bf4ffeu
#define SD_IL2CPP_SC_get_height_W1  0xb00027b3u

#endif /* SD_IL2CPP_OFFSETS_H */
